"""ffmpeg-dependent checks: the fake against reality, and structure that composes.

Marked ``video`` and excluded from ``make test`` and ``ci-local``, so the offline
suite stays dependency-free, which it has been from the start. Run them with
``make test-video``.

**These cost nothing.** They read images and audio from a committed run and
encode locally: no API call, no key, no network. So they can be repeated freely,
which is what makes two runs cheap.
"""

import subprocess
from pathlib import Path

import pytest

from sparkstory.models.fake_clip_maker import TINY_MP4
from sparkstory.video.assemble import assemble
from sparkstory.video.kenburns import FPS, HEIGHT, WIDTH, KenBurnsClipMaker, frames_for
from sparkstory.video.probe import probe_audio_duration, probe_frame_count

pytestmark = pytest.mark.video

#: A run with six page images, six page MP3s and story.mp3 -- the only committed
#: run carrying both halves. Its per-page durations are recorded in the spec.
_RUN = Path("outputs/20260813-214645-a-child-who-plants-a-seed-and-waits-for-")


def _stream_properties(path: Path) -> dict[str, str]:
    """codec, pixel format and size of a file's first video stream."""
    out = subprocess.run(
        [
            "ffprobe",
            "-v",
            "error",
            "-select_streams",
            "v:0",
            "-show_entries",
            "stream=codec_name,pix_fmt,width,height",
            "-of",
            "default=noprint_wrappers=1",
            str(path),
        ],
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return dict(line.split("=", 1) for line in out.strip().splitlines() if "=" in line)


@pytest.fixture(scope="module")
def _run_exists() -> None:
    if not (_RUN / "page-01.mp3").exists():
        pytest.skip(f"{_RUN} is not on disk")


async def test_the_fake_matches_what_the_real_encoder_produces(
    tmp_path: Path, _run_exists: None
) -> None:
    """A fake must be valid in the format the real provider returns, and this
    project has already paid for getting that wrong once.

    ``FakeSpeechProvider``'s canned MP3 was MPEG-1 while the provider returned
    MPEG-2. Both legal; every offline test passed; ``story.mp3`` was corrupt. A
    fake wrong in a *plausible* direction passes the tests written about it.

    ``TINY_MP4`` was generated by this encoder rather than hand-written, so this
    is the guard against the two drifting apart later -- if the settings in
    ``kenburns.py`` change, the fake stops describing what the workflow produces
    and this fails.

    Probed properties rather than byte equality: bytes would differ on any
    encoder build while proving nothing, and codec/pixel-format/size are what
    actually have to match for clips to concatenate.
    """
    clip = await KenBurnsClipMaker().make_clip(
        (_RUN / "page-01.jpg").read_bytes(), 1.0, 1
    )
    real = tmp_path / "real.mp4"
    real.write_bytes(clip.data)
    fake = tmp_path / "fake.mp4"
    fake.write_bytes(TINY_MP4)

    assert _stream_properties(fake) == _stream_properties(real)
    assert clip.video_format == "mp4"


async def test_a_clip_has_exactly_the_frames_it_was_asked_for(
    tmp_path: Path, _run_exists: None
) -> None:
    """Every move, not only the one the spike happened to run.

    Three of the four were unexercised when they were written, and a wrong
    expression produces a clip of the wrong length rather than an error -- which
    the assembly would then silently absorb as drift.
    """
    maker = KenBurnsClipMaker()
    image = (_RUN / "page-01.jpg").read_bytes()

    for page in (1, 2, 3, 4):
        clip = await maker.make_clip(image, 2.0, page)
        path = tmp_path / f"clip-{page}.mp4"
        path.write_bytes(clip.data)
        assert await probe_frame_count(path) == frames_for(2.0), f"page {page}"

    held = await maker.make_clip(None, 2.0, 1)
    card = tmp_path / "held.mp4"
    card.write_bytes(held.data)
    assert await probe_frame_count(card) == frames_for(2.0)
    assert _stream_properties(card)["width"] == str(WIDTH)
    assert _stream_properties(card)["height"] == str(HEIGHT)


async def test_the_assembled_video_has_exactly_the_frames_it_should(
    tmp_path: Path, _run_exists: None
) -> None:
    """Assert structure that composes, not one piece in isolation.

    A per-clip check cannot catch a broken concat; single-frame assertions are
    exactly what let the corrupt ``story.mp3`` through. This walks the *finished*
    file.

    Counted with ``-count_frames`` rather than read from the container header: a
    concatenated stream's header duration is an estimate, so asserting on it
    would be a check with no room to fail.
    """
    maker = KenBurnsClipMaker()
    clips: list[Path] = []
    audios: list[Path] = []
    expected = 0

    for page in (1, 2, 3):
        audio = _RUN / f"page-{page:02d}.mp3"
        duration = await probe_audio_duration(audio)
        expected += frames_for(duration)

        clip = await maker.make_clip(
            (_RUN / f"page-{page:02d}.jpg").read_bytes(), duration, page
        )
        path = tmp_path / f"clip-{page:02d}.mp4"
        path.write_bytes(clip.data)
        clips.append(path)
        audios.append(audio)

    destination = await assemble(clips, audios, tmp_path / "story.mp4")

    actual = await probe_frame_count(destination)
    assert actual == expected, (
        f"{actual} frames against {expected} expected -- "
        "the concat dropped or duplicated frames"
    )


async def test_audio_and_video_still_agree_at_the_last_page(
    tmp_path: Path, _run_exists: None
) -> None:
    """Drift accumulates, so the assertion that matters is at the end.

    A one-frame-per-page error is invisible on page 1 and half a second off by
    page 6. This is why ``frames_for`` rounds rather than truncating -- and the
    tolerance is deliberately *not* per-page, or it would grow to accommodate
    exactly the defect it exists to catch.
    """
    maker = KenBurnsClipMaker()
    clips: list[Path] = []
    audios: list[Path] = []
    audio_total = 0.0

    for page in range(1, 7):
        audio = _RUN / f"page-{page:02d}.mp3"
        duration = await probe_audio_duration(audio)
        audio_total += duration

        clip = await maker.make_clip(
            (_RUN / f"page-{page:02d}.jpg").read_bytes(), duration, page
        )
        path = tmp_path / f"clip-{page:02d}.mp4"
        path.write_bytes(clip.data)
        clips.append(path)
        audios.append(audio)

    destination = await assemble(clips, audios, tmp_path / "story.mp4")

    video_seconds = await probe_frame_count(destination) / FPS
    # Half a frame per page is the most rounding can ever cost, so this is the
    # tightest bound the design permits -- and it does not grow with page count
    # the way a per-page tolerance would.
    assert abs(video_seconds - audio_total) < (0.5 / FPS) * 6
