from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
# This line sets up loggers basically.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The URL comes from Settings, NOT from alembic.ini, and the ini's own
# `sqlalchemy.url` is left blank deliberately. A database URL carries a password,
# alembic.ini is committed, and .env is not -- pre-commit actively refuses to
# commit it. One source of truth also means `alembic upgrade head` and the running
# server cannot disagree about which database they mean.
from sparkstory.config import settings  # noqa: E402

# Importing the models registers the chunks table on Base.metadata. Nothing here
# uses the symbol directly, which is why it carries a noqa.
from sparkstory.db import models  # noqa: E402,F401
from sparkstory.db.base import Base  # noqa: E402

if not settings.database_url:
    # Without this, engine_from_config fails on an empty URL with a message about
    # SQLAlchemy internals that names nothing an operator can act on. Rule 5: a
    # domain condition deserves a message naming the variable to set.
    raise SystemExit(
        "DATABASE_URL is not set, so there is no database to migrate. "
        "Set it in .env, or start one with `docker compose up -d postgres`."
    )

config.set_main_option("sqlalchemy.url", settings.database_url)

# Autogenerate is deliberately NOT relied on for the chunks table: its name
# depends on the embedding registry entry, so it is not knowable when this module
# is imported. The metadata is still pointed here so that a future ordinary table
# (books, canon) can be autogenerated normally.
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL
    and not an Engine, though an Engine is acceptable
    here as well.  By skipping the Engine creation
    we don't even need a DBAPI to be available.

    Calls to context.execute() here emit the given string to the
    script output.

    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode.

    In this scenario we need to create an Engine
    and associate a connection with the context.

    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
